name: build-and-publish-sharelatex

on:
  push:
    branches:
      - 'main'
    paths:
      - 'sharelatex/*'

jobs:
  docker:
    name: Build and push sharelatex image to quay.io
    environment: production
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Get image tags
        id: image_tags
        run: |
          echo -n ::set-output name=IMAGE_TAGS::
          if [[ "${GITHUB_REF}" =~ refs/tags/(.*) ]]; then
              echo ${BASH_REMATCH[1]}
          else
              echo ${{ github.sha }}
          fi

      -
        name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          push: true
          tags: quay.io/schnell18/sharelatex:${{ steps.image_tags.outputs.IMAGE_TAGS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Print image url
        run: echo "Image pushed to ${{ steps.build-and-push.outputs.imageid }}"
