name: java-runtime-jdk-17

on:
  push:
    branches:
      - 'main'
      - 'podman'
    paths:
      - java/runtime/alpine/17/jdk/Dockerfile
      - java/runtime/alpine/17/version.json

jobs:
  build:
    name: Build and push image
    environment: production
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Install qemu dependency
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static

    - name: Get zulu version
      id: zulu-version
      run: |
        echo -n ::set-output name=ZULU_VERSION::
        jq -r '.zuluVersion' java/runtime/alpine/17/version.json

    - name: Get OpenJDK version
      id: openjdk-version
      run: |
        echo -n ::set-output name=OPENJDK_VERSION::
        jq -r '.openjdkVersion' java/runtime/alpine/17/version.json

    - name: Get build number
      id: build-number
      run: |
        echo -n ::set-output name=BUILD_NO::
        jq -r '.build' java/runtime/alpine/17/version.json

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: java-runtime-jdk
        build-args: |
          OPENJDK_VERSION=${{ steps.openjdk-version.outputs.OPENJDK_VERSION }}
          ZULU_VERSION=${{ steps.zulu-version.outputs.ZULU_VERSION }}
        tags: ${{ steps.openjdk-version.outputs.OPENJDK_VERSION }}-${{ steps.zulu-version.outputs.ZULU_VERSION }}-${{ steps.build-number.outputs.BUILD_NO }}-alpine
        archs: amd64, arm64
        context: java/runtime/alpine/17/jdk/
        containerfiles: java/runtime/alpine/17/jdk/Dockerfile

    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags:  ${{ steps.build-image.outputs.tags }}
        registry: quay.io/${{ secrets.REGISTRY_USERNAME }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
