name: build-and-publish-jupyterlab

on:
  push:
    branches:
      - 'main'
    paths:
      - 'jupyterlab/*'

jobs:
  docker:
    name: Build and push jupyterlab image to quay.io
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Get image version
        id: image-version
        run: |
          echo -n ::set-output name=IMAGE_VERSION::
          jq -r '.imageVersion' jupyterlab/version.json

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: "./jupyterlab"
          platforms: linux/amd64
          push: true
          tags: quay.io/schnell18/scipy-notebook:${{ steps.image-version.outputs.IMAGE_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Print image url
        run: echo "Image pushed to ${{ steps.build-and-push.outputs.imageid }}"

